### ISSUE TITLE
Typescript Definition

### ISSUE THREAD

**Issue by ezrayoung** [React95/React95#126]
Has there been any consideration for adding a Typescript definition file, or even migrating the project to Typescript to generate them automatically?

I plan to use this package in an upcoming Reason project, so I'd rather not reimplement the type definitions by writing bindings, if there is already progress being made in this area.

If Typescript is something that you consider worth having on the roadmap, I'm more than happy to contribute where I can.

**Comment by ggdaltoso** [comment]
🤔 

Hi @ezrayoung ! Thanks for bringing this subject!

Well, at the beginning of the development of React95 we discuss using TS to build this library but, it came to us that it wouldn't add too much in the code, because most components are just styled-components itself.

Honestly, I had no idea that someone would use React95 in a TS project and we never thought to add the support for it. And, here we are!

I like TS and I would love to discuss the implementation with you.

Since this repo is now a [monorepo](https://github.com/React95/React95/pull/117), which is the best approach to add TS here? The `tsconfig` should be at the root, to be accessible to all packages, or it should be only at [@react95/core](https://github.com/React95/React95/tree/master/packages/core)?
IMO, it could be in the root and all packages could add the TS support. What do you think?

And thank you for willing to contribute, man! It will be awesome!

**Comment by ezrayoung** [comment]
@ggdaltoso I ended up writing the Bucklescript bindings that I needed for my project, but I'll still be glad to work on what's needed to implement Typescript here!

I don't have much experience with monorepos, so I did some quick searching and came across this example: https://github.com/DylanVann/typescript-monorepo-example. Is this similar to what you are suggesting?

**Comment by ggdaltoso** [comment]
Yes!

In this example, all packages are written in TS, which I would like to see here in 95.

Could you start? =D

**Comment by ezrayoung** [comment]
I went ahead and started work on this tonight. I'll try not to spend too much time coming up with compiler options and linting rules, but I'll be glad to get some input on them.

**Comment by DanielRosenwasser** [comment]
I have something mostly fleshed out - I'd highly recommend not to maintain `.d.ts` files on this repo unless you're all very well-experienced with TypeScript. Unless that's the case, I'll probably send a pull request to DefinitelyTyped when I get the chance, and some eyes on that would be extremely appreciated.

**Comment by hammadj** [comment]
@DanielRosenwasser Any updates on the definitions? Would love to help get it through.

**Comment by GongT** [comment]
You should put `compilerOptions` in a `tsconfig` at the root.

And then use `extends` + `rootDir`&`outDir` in a `tsconfig` at every sub project.

**Comment by ggdaltoso** [comment]
Guys!

Just to let you know, I'm working on this in #174! 🎉 

I would love to have some feedback on it since I'm not a TS expert.

I'm working on `@react95/core` first and `@react95/icons` after. 

What you guys think would be better for `@react95/icons` for handling with `.ico` typings?

**Comment by ggdaltoso** [comment]
@DanielRosenwasser @hammadj @hammadj @GongT 

Hey guys!

I'm not a TS specialist and I would love it if I could have some feedback on my current work on #174 

I'm refactoring all components first and then the tests. There is a detailed description in the PR showing whether a component is already rewritten as TS or not.
