### ISSUE TITLE
NextJS - Global CSS cannot be imported from within node_modules

### ISSUE THREAD

**Issue by mctang719** [React95/React95#205]
error - ./node_modules/@react95/icons/icons.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/@react95/core/ThemeProvider/ThemeProvider.js

**Comment by TomAndril** [comment]
I'm having the same problem, been trying to fix it, unfortunately without luck. Maybe someone who already stepped over this same issue can lend us a hand :)

**Comment by tcK1** [comment]
Not sure if this can help, but have you guys looked into https://github.com/martpie/next-transpile-modules? 🤔

**Comment by TomAndril** [comment]
> Not sure if this can help, but have you guys looked into https://github.com/martpie/next-transpile-modules? 🤔

Yes, I've tried it without luck, it still complain about the css module imported from node_modules

**Comment by ggdaltoso** [comment]
I think I know how to fix this.

1. Need to remove [the line importing the CSS file in ThemeProvider](https://github.com/React95/React95/blob/master/packages/core/components/ThemeProvider/ThemeProvider.tsx#L7).
2. Clean up the [assets](https://github.com/React95/React95/tree/a014647fe387420d1dd5b56da5eee8ee6ece7576/packages/core/components/shared/assets) folder. There are a lot of garbage and some PNGs files that could easily be something like `base64`. This would prevent the app which is using `@react95/core` to add specific loaders/some hacky stuff/transpilers.
3. Edit the docs on README by adding the steps for adding the `@react95/icons/icons.css` file.

I think this is also a breaking change.

I can do this but it would be nice if some of you guys could contribute. 
What do you think @tcK1 @mctang719 @TomAndril ?

**Comment by TomAndril** [comment]
> I think I know how to fix this:
> 
> 1. Need to remove [the line importing the CSS file in ThemeProvider](https://github.com/React95/React95/blob/master/packages/core/components/ThemeProvider/ThemeProvider.tsx#L7).
> 2. Clean up the [assets](https://github.com/React95/React95/tree/a014647fe387420d1dd5b56da5eee8ee6ece7576/packages/core/components/shared/assets) folder. There are a lot of garbage and some PNGs files that could easily be something like `base64`. This would prevent the app which is using `@react95/core` to add specific loaders/some hacky stuff/transpilers.
> 3. Edit the docs on README by adding the steps for adding the `@react95/icons/icons.css` file.
> 
> I think this is also a breaking change.
> 
> I can do this but it would be nice if some of you guys could contribute.
> What do you think @tcK1 @mctang719 @TomAndril ?

I absolutely would like to collaborate, It turns out I'm kinda new when it comes to this. I've been trying to implement your solution but without any luck. I'm not sure which files should I delete into the assets folder, also I'm deleting the CSS file import in the ThemeProvider file but it stills complaining about this import. I'm afraid that I'm not confident enough to fix it, but maybe with some guidance I would be able to fix it 😄

**Comment by ggdaltoso** [comment]
Great @TomAndril !

I already did some cleaning on the [`fix/build`](https://github.com/React95/React95/tree/fix/build) branch. 

I've also removed [the line from ThemeProvider](https://github.com/React95/React95/commit/768badb4b740ec96c5fc9675287a333a54e668d9#diff-e84355811809fc1b7a9d7c3073f57a55892a75e5892accc89d101231c347c306L7), importing the CSS icons file.

The storybook seems to be working fine and we just need to set up the build process.

Since the assets are very small like [Checkbox check](https://github.com/React95/React95/blob/fix%2Fbuild/packages/core/components/Checkbox/imgs/check.svg) and [Radio circle](https://github.com/React95/React95/blob/fix%2Fbuild/packages/core/components/RadioButton/imgs/radio-checked.png), for example, I was thinking about the possibility to send them as `base64` and maybe use [babel-plugin-inline-import-data-uri](https://www.npmjs.com/package/babel-plugin-inline-import-data-uri) to do this work for us.

What do you think?

**Comment by ggdaltoso** [comment]
@TomAndril @mctang719 

I've just published an alpha release fixing this issue.
[@react95/core@2.13.5-alpha.0](https://www.npmjs.com/package/@react95/core/v/2.13.5-alpha.0).

Could you guys, please, check if it is working?

In addition to the alpha version, there is still some config you may need to add to your application. You can check if the doc is enough [here](https://github.com/React95/React95/tree/alpha/packages/core#nextjs).

**Comment by ggdaltoso** [comment]
Just to see if it is working, I did a quick start project following the steps from the [NextJS official guide](https://nextjs.org/learn/basics/create-nextjs-app) and create [this repo](https://github.com/ggdaltoso/nextjs-blog)

**Comment by mctang719** [comment]
Works like a charm! Thank you so much @ggdaltoso !

**Comment by TomAndril** [comment]
It is working absolutely fine! Thank you so much @ggdaltoso
