### ISSUE TITLE
Import icons when used instead of adding to CSS

### ISSUE THREAD

**Issue by kirkobyte** [React95/React95#235]
This is a bit more of a performance optimisation/nice-to-have than anything critical. But if `@react95/icons` exported individual icons instead of adding all of them to [this CSS file](https://github.com/React95/React95/blob/master/packages/icons/icons.css), most of the size for consumers could be cut down.

Taking a look at my project's size, the majority of it is the CSS file containing icons: 
![image](https://user-images.githubusercontent.com/6798667/110915061-7d068d80-8317-11eb-9977-8721f9b26dd8.png)

If the current set-up is to avoid consumers needing to set-up `.png`/`.ico` imports, I think this could still be done by having each icon exported as a React component looking something like this:
```tsx
export const Access = () => (
  <img src={url('./src/png/access_110_16x16_4bit.png')} />
);
```

**Comment by ggdaltoso** [comment]
Hi again, @kirkobyte ! Glad to see you again here!

Well... there is some history here... 

In the beginning, all icons were exported as `.ico`, since each file [can contain multiples sources](https://en.wikipedia.org/wiki/ICO_(file_format)). 

To manage all those images inside a `ico` file, I used to use this custom hook:
 - [useIcon](https://github.com/React95/React95/commit/61764656b1be560b5225c6be06804409e7973f1e#diff-6ba01ba274518784f6ffc43cd12d57e91d4fdc9cca765445e0291cdfc5362124)
 - [Icon Component](https://github.com/React95/React95/commit/61764656b1be560b5225c6be06804409e7973f1e#diff-d92063017c4312001baaa99ae050070ae595dec795d4af9c184e85d89481ff95)

Everything was fine there. I was able to consume each of them, importing on demand.

So, @kaiofelipejs opened #189 and I spend a lot of time trying to figure out what was happening with the Icon package.

Without any solutions yet, I decided to make a CSS file and then transforming all `.ico` to png. As you can see [here](https://github.com/React95/React95/tree/master/packages/icons/src/icons), we still get the `.ico` assets.

A lot of work done here to make `@react95/icons` a CSS file (an be able to be used in an application regarding React), trying to make it better but, as @kaiofelipejs [said](https://github.com/React95/React95/issues/189#issuecomment-756354286), it turns to create another issue, opened by you too. 

At this point, I really don't know what to do 😔

> ```tsx
> export const Access = () => (
>   <img src={url('./src/png/access_110_16x16_4bit.png')} />
> );
> ```

So, do you think we could export all of them as you mentioned and keep the CSS file to those who are already importing as a CSS file?

If we export all of them as a separated component, what's will be the future of [`@react95/core/Icon`](https://github.com/React95/React95/blob/master/packages/core/components/Icon/Icon.tsx)?

**Comment by kaiofelipejs** [comment]
I like the idea of export separated components. This remember big packages like [ant-design-icons ](https://github.com/ant-design/ant-design-icons/tree/bb475e58d967236b5be03073eb0ad6e4bb03719b/packages/icons-react/src/icons)

**Comment by kirkobyte** [comment]
Ah right so there's been a bit of back and forth there 😅 

Yeah, we should be able to keep both! As long as we still generate the CSS file, it could be used by anyone.

We could either make the CSS only available for people who want to use it directly, or keep `@react95/core/Icon` and specify that it will only work if you import the CSS. But I think it might be advisable to avoid that.

**Comment by kirkobyte** [comment]
If we want to make `@react95/icons` a bit more automated, we could use a Node script to auto-generate both the CSS file and the components.

I think we should be able to knock out both the CSS & component generation in the same file. I think something along these lines would do it:
```tsx
import fs from 'fs';
import ICO from 'icojs';
import path from 'path';

const ICONS_FOLDER = './src/icons';

const iconComponentTemplate = (
  name: string,
  images: ICO.ParsedImage[],
  buffers: Record<number, string>,
) => `
import React from 'react';

const buffers = ${JSON.stringify(buffers)};
type IconProps = React.DetailedHTMLProps<
  React.ImgHTMLAttributes<HTMLImageElement>,
  HTMLImageElement
> & {
  size: ${images.map(image => image.width).join(' | ')};
}

export const Icon${name}: React.FC<{IconProps}> => ({size, ...rest}) => (
  <img {...rest} url={buffers[size]} />
);
`;

const makeCssClass = (iconName: string, image: ICO.ParsedImage) => `
  .${iconName}_${image.width}x${image.height}_${image.bpp} {
    width: ${image.width};
    height: ${image.height};
    background-image: url(${image.buffer});
  }
`;

const files = fs.readdirSync(ICONS_FOLDER);
let css = '';

files.forEach(async fileName => {
  const iconName = fileName.split('.')[0];
  const buffer = fs.readFileSync(path.join(ICONS_FOLDER, fileName));
  const images = ICO.parseSync(buffer, 'image/png');

  const buffers = {};
  images.forEach(image => {
    css = css + makeCssClass(iconName, image);

    buffers[image.width] = image.buffer;
  });

  const componentContents = iconComponentTemplate(
    fileName.split('.')[0],
    images,
    buffers,
  );

  fs.writeFileSync('<wherever the output goes>', componentContents);
});

fs.writeFileSync('./icons.css', css);
```

**Comment by kirkobyte** [comment]
I think if we did this, we could use the new generated `Icon*` components internally and leave it up to users to switch form `Icon` to the smaller `Icon*` components without needing to make it a breaking change

**Comment by kirkobyte** [comment]
I can open a PR attempting this if you’d like 😊

**Comment by ggdaltoso** [comment]
🤔 

It seems to be the best option!

I'm just not sure about the Icons, from `@react95/core`. Maybe we drop it. What do you think? If we do what you're suggesting, and create one component for each `.ico`, the `Icon` will become obsolete, IMHO. 

Also, I'm ok with publishing a breaking change. If it is for the best, why not? 

It would be awesome to have another PR for you!
It would be a lot of refactoring, I think, @kirkobyte, so let me know If I can help you with anything!

**Comment by kirkobyte** [comment]
Great! I've got a local branch where I've been working on this. It's taking a bit of time to get the Storybook icon demo working as it previously did. But the rest of it hasn't been too bad to refactor :)

**Comment by kirkobyte** [comment]
I'll try get it into a state where I can open a PR this weekend
