### ISSUE TITLE
TaskBar window buttons rendering double

### ISSUE THREAD

**Issue by Juuddi** [React95/React95#369]
## Description

I've just recently installed `react95@core` and have been experimenting with components. Started off with the `taskbar` and noticed that when adding a `modal` to the list and opening the modal from the taskbar, it renders 2 window buttons within the frame.  They continue to multiply as you open and close the modal. 

## Screenshots
<img width="874" alt="Screen Shot 2022-09-09 at 7 01 37 PM" src="https://user-images.githubusercontent.com/98721462/189460323-9d96d668-bccd-4ab7-81a2-17d7c5adfe0a.png">

Here's what it renders after a few modal clicks.

## Resolution
When working with `chakra-ui` last week, I ran into a relatively similar issue. The issue can be found [here](https://github.com/chakra-ui/chakra-ui/issues/6317). Seems that React 18 breaks certain modal open/close features, and can be temporarily solved by removing `React.StrictMode`.  

## Additional Information
- Bug only seen on React 18
- I'd love to fix this myself but am not experienced enough of a react dev to do so. Just wanted to make y'all aware, thanks for this amazing library!

**Comment by ggdaltoso** [comment]
That's weird!
Could you provide a repo to help me to reproduce such behavior? 

And I'd love to guide you in this fix, if you want to. 

Thanks for opening this issue and for using React95 library!

**Comment by Juuddi** [comment]
Thanks for responding @ggdaltoso, think I fixed this a while back. Can't remember exactly what was causing it but think it was some package mis-versioning or improper use of state for modal toggling. Sorry for the bother!

Absolutely love React95, thanks for all the great work!

**Comment by ggdaltoso** [comment]
I'm glad that you're enjoining React95 so far!

I hope this issue doesn't get you away from contributing! 
I'd love to see a PR from you! <3

**Comment by ghazian** [comment]
Just to give a little bit of context if anyones encountering this problem, if you're doing a react project with React95, and TaskBar is rendering double the component is because in development mode, React StrictMode intentionally double-invokes certain lifecycle methods (including constructor, render, and others) to help identify side effects. This does not happen in production builds. However, this shouldn't affect how components appear in the DOM but is worth noting if you're seeing logs or behavior executed twice. 👍 

Usually to fix this you'd just remove Strict mode on your `index.js` file or `App.js` file
