### ISSUE TITLE
Scrolling issue in storybook

### ISSUE THREAD

**Issue by Juuddi** [React95/React95#408]
Cleaning up some older code that uses this package and was taking a look at the storybook to find some new icons. Noticed that scrolling is disallowed, thus preventing me from scrolling through any of the icons :(

Did some digging and found importing `GlobalStyle` into [`Frame.tsx`](https://github.com/React95/React95/blob/master/packages/core/.storybook/decorators/Frame.jsx) here pulls in an [`overflow: hidden`](https://github.com/React95/React95/blob/3416b9a5710c518a8ccf135855c08d1f0558b429/packages/core/components/GlobalStyle/GlobalStyle.tsx#L44C5-L44C13) style on the body of the storybook frames. Setting overflow to hidden seems to be essential within actual applications built with React95 as it prevents the desktop from being scrollable, but using this in the storybook prevents some of the stories from being fully viewable by users like me.

**Comment by ggdaltoso** [comment]
I noticed that yesterday 😂 

We had overflow previously on GlobalStyle but it wasn't the right place to add it.
@rfoel [proposed some changes](https://github.com/React95/React95/pull/376#issuecomment-1656841346) and we shipped a new version with the fix a while ago.

But removing the overflow from GlobalStyle breaks places where it is necessary, as you noticed. I think this can be fixed in some storybook configuration.

Would you like to contribute?

**Comment by Juuddi** [comment]
> Would you like to contribute?

I'm not super familiar with Storybook config stuff and thus was hesitant to open a PR, but I'd be open to fork it and fix it. I'll put up a PR at some point in the next few days and close out this issue.

Read thru the `CONTRIBUTING.md`, anything else I should be aware of before I put up a PR?
