### ISSUE TITLE
Assets folder isn't builded

### ISSUE THREAD

**Issue by allyssonsantos** [React95/React95#81]
It throws an error when use some component that render an Icon.

To fix  that,  the assets folder need to be present inside dist folder after build process end.

**Comment by Zachari** [comment]
Wouldn't this issue be more suited to a solution using Webpack and loaders (style-loader, css-loader, url-loader, file-loader, etc)? There are ways to accomplish this via Babel plugins, but they're all build on Webpack anyway. Babel is a transpiler first and foremost, not a bundler. All these plugins are doing is transforming the imports at build time.

Using Webpack alongside Babel, you could do all the same things you're doing currently with Babel and simply add the transpilation to the the bundling process, avoid these resolution issues, and get the benefit of additional tools at your disposal during build (minifying code, SASS or whatever else for styling, autoprefixing, etc).

I could be missing some key point that makes this a less than optimal solution, but I feel like Webpack is the move here.

**Comment by allyssonsantos** [comment]
Hi @Zachari 

Me and @ggdaltoso have searched a lot about this when we were thinking about bundling this library.

After all the content that we found about this, we decided that we do not need Webpack, Rollup, Parcel or any bundler tool. We reached the idea that Webpack is more for application than for libraries.

And about using any kind of css loader, how we are not using css files, we do not need it.

We just need to transpile our code, the code minification will be maded by the application that will use React95.

Here's some content that we read about this: https://medium.com/@lawliet29/tree-shaking-in-real-world-what-could-go-wrong-b398c2b2ebbb

But we might be wrong, so we accept PR's and other suggestions!

Thank you for your point of view.

**Comment by Zachari** [comment]
That's understandable. I suggested Webpack because it's the one I have the most experience with when it comes to static assets. Admittedly, Webpack doesn't seem to be the best fit for a library. However, I do disagree that bundlers in general are a good fit towards applications only. Rollup, in particular, appears to be perfect for libraries, especially in situations such as this. However, I can't tinker with it until tomorrow so I can't say whether or not it'd be optimal here. I will tomorrow, however.

I don't fault the logic behind the choice, though. If that's the approach, simply including them in a shared folder to avoid resolution issues seems to be the way to go.
