### ISSUE TITLE
I would love to create the FileSystem loading state

### ISSUE THREAD

**Issue by davesnx** [React95/React95#84]
I would love to have the paper animation as an Icon in React95, as well the folder with the paper "inside".

Then I would be able to create the famous animation: https://www.youtube.com/watch?v=lQkJhCfk_Oo

What do you think?

**Comment by Avi98** [comment]
if it's okay I would love to work on this issue. Would be fun to build a loading icon like this.

**Comment by allyssonsantos** [comment]
Hi @davesnx and @Avi98 :smiley: 

I would love this too, so for me is absolutely ok!
I think you can use `Alert` or `Modal` component to help building this animation.

Thank you guys.

**Comment by Avi98** [comment]
@davesnx I will be needing some help in order to create this component. I was thinking of creating a modal with two folder icons, one with paper in the folder icon and the other one will be an empty folder icon. 
My concern over here is how will I rotate paper from the left bottom while moving from one folder icon to another.

**Comment by davesnx** [comment]
I would use a gif for the animation of the paper, or a simple "sprite" and match the velocity of the gif(or sprite) with the curve of the animation.

**Comment by ggdaltoso** [comment]
@davesnx @Avi98 

Is this still a thing for you?

**Comment by davesnx** [comment]
Was a wish from 2 years ago, not sure if I would define it as a thing for me haha

Thanks for the following up, happy to close it thought.
